/*
 * examples — SAMPLES.md as a queryable index of working apps.
 *
 * The question this answers is "has somebody already built X", and until now
 * nothing here could. `capabilities` answers the neighbouring one — "can
 * abap2UI5 express this UI5 feature at all" — from samples-controls' 416 ports
 * of the demo kit. Neither answers the other: a control being expressible says
 * nothing about how an app that uses it is put together, and a pattern being
 * demonstrated says nothing about which controls are reachable.
 *
 * Same shape as capabilities on purpose, for the same reason: SAMPLES.md is
 * PARSED ON EVERY QUERY rather than indexed into a generated artefact, so what
 * the agent sees is always exactly what the file says. The file is itself
 * generated (`npm run launchpad` in the samples repository) from the classes,
 * and a gate there refuses a tile without `@keywords`, so the search terms
 * this reads cannot quietly go missing.
 *
 * What comes back is a POINTER, never a copy: class name and repository path.
 * The agent reads the class - a whole app that compiles, renders and is
 * downported to three releases - instead of a fragment that would have to be
 * kept in step with it here.
 *
 * Parsed shape per entry:
 *   { area, section, title, sub, label, keywords, cls, path }
 */
import fs from 'fs';
import path from 'path';
import { resolveSamples } from './repos.mjs';

function samplesFile() {
  const repo = resolveSamples();
  if (!repo) throw new Error('samples checkout not found — set SAMPLES_HOME or clone it as a sibling (the sample catalogue lives there)');
  const file = path.join(repo, 'SAMPLES.md');
  // the checkout being there does not make the file there: an older revision
  // predating the catalogue, a half-finished pull, a rename upstream
  if (!fs.existsSync(file)) {
    throw new Error(`the samples checkout has no SAMPLES.md (looked in ${file}) — update it (git pull); the catalogue is generated by \`npm run launchpad\``);
  }
  return file;
}

/* One catalogue row:
 *
 *   | **Basics I** — Hello World<br><sub>hello world minimal</sub> | [`Z2UI5_CL_SMP_APP_493`](src/01/z2ui5_cl_smp_app_493.clas.abap) |
 *
 * The bold half is present only where the row carries a header of its own
 * (generate-samples-md drops one that would just repeat its section), so both
 * shapes have to parse. */
const ROW = /^\|\s*(?:\*\*(?<title>[^*]+)\*\*\s*(?:—|--)\s*)?(?<sub>[^|<]*?)\s*(?:<br><sub>(?<keywords>[^<]*)<\/sub>)?\s*\|\s*\[`(?<cls>[A-Z0-9_]+)`\]\((?<path>[^)]+)\)\s*\|/;

export function parseExamples(rawText = null) {
  const text = rawText ?? fs.readFileSync(samplesFile(), 'utf8');
  const entries = [];
  let section = '';
  for (const line of text.split('\n')) {
    const head = /^#{2,3}\s+(.+?)\s*$/.exec(line);
    if (head) { section = head[1].replace(/[*`]/g, '').trim(); continue; }
    const m = ROW.exec(line);
    if (!m) continue;
    const g = m.groups;
    entries.push({
      section,
      // a row without its own header is titled by the section it sits under
      title: (g.title || section).trim(),
      sub: (g.sub || '').trim(),
      keywords: (g.keywords || '').trim(),
      /* What to call it in one line, so a caller does not reassemble it.
       * Deliberately reads the RAW header rather than `title`: a row whose
       * header would repeat its section does not carry one, and `title` falls
       * back to the section there - announcing the F4 value-help sample as
       * "Popup" rather than as what it does. */
      label: [g.title?.trim(), (g.sub || '').trim()].filter(Boolean).join(' — ')
        || section,
      cls: g.cls,
      path: g.path,
      // src/01 is the supported set; src/00 is experimental (97) or a test app
      // (98), which an agent should weigh differently when picking one to copy
      area: g.path.startsWith('src/01') ? 'samples' : 'experimental-or-test',
    });
  }
  return entries;
}

/** Every term has to appear somewhere in the entry - the same AND semantics
 *  `searchCapabilities` uses, so a two-word query narrows rather than widens. */
export function searchExamples({ query, area, limit = 20, rawText = null } = {}) {
  let entries = parseExamples(rawText);
  if (area) entries = entries.filter((e) => e.area === area);
  if (query) {
    const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
    const hay = (e) => `${e.section} ${e.title} ${e.sub} ${e.keywords} ${e.cls}`.toLowerCase();
    entries = entries.filter((e) => terms.every((t) => hay(e).includes(t)));
    /* A hit in the KEYWORDS is a hit on a word somebody chose to be found by;
     * a hit in the title or the section may be incidental. Ranked, not
     * filtered - the weaker matches are still the answer when there are no
     * others. */
    const score = (e) => {
      const k = e.keywords.toLowerCase();
      return terms.filter((t) => k.includes(t)).length;
    };
    entries = [...entries].sort((a, b) => score(b) - score(a));
  }
  return limit > 0 ? entries.slice(0, limit) : entries;
}

export function exampleSummary(rawText = null) {
  const entries = parseExamples(rawText);
  const byArea = {};
  const bySection = {};
  for (const e of entries) {
    byArea[e.area] = (byArea[e.area] || 0) + 1;
    bySection[e.section] = (bySection[e.section] || 0) + 1;
  }
  return { total: entries.length, byArea, sections: Object.keys(bySection).length };
}
