/* scaffold_app — the files a new abap2UI5 project starts from, named after the
 * app the agent is actually writing.
 *
 * `app_guide` tells an agent how to write the CLASS. That is the half it can
 * do: the guide is self-contained and the class is ABAP. The half it cannot
 * invent is everything around the class — which abaplint release the framework
 * is pinned at and under which key, what `abap2ui5lint.jsonc` has to say for
 * the render gate to run rather than skip, the `.clas.xml` sidecar whose
 * CLSNAME must match the class or the object does not import at all, and the
 * `.abapgit.xml` that decides where abapGit puts any of it.
 *
 * Those live in abap2UI5/app-template, which the ecosystem already calls the
 * place to begin. Served from the checkout rather than embedded, for the same
 * reason nothing else here is embedded: a copy in this repository would be a
 * second answer to "what does a new project look like", and the template moves.
 *
 * Renaming is part of the answer, not a follow-up step. The template's own
 * scripts/rename.mjs exists because the class name lives in the ABAP *and* in
 * the sidecar's CLSNAME, and renaming half of it produces an object that looks
 * right and does not activate. This applies the same three substitutions, so
 * what comes back is already the agent's project.
 */
import fs from 'fs';
import path from 'path';

/* What a new project takes. Deliberately not "everything in the template":
 * README.md and LICENSE are the template's identity, package-lock.json is
 * enormous and regenerated by `npm install` anyway, and scripts/ are the
 * template's own maintenance tools (rename.mjs has nothing left to rename
 * once this has renamed it; check-pin.mjs checks a pin in files this does
 * not serve). AGENTS.md IS included: a project whose agent has no briefing is
 * the gap this whole tool exists to close. */
export const TEMPLATE_FILES = [
  'AGENTS.md',
  'abaplint.jsonc',
  'abap2ui5lint.jsonc',
  'package.json',
  '.gitattributes',
  '.abapgit.xml',
  '.github/workflows/check.yml',
  '.github/dependabot.yml',
  '.claude/settings.json',
  'src/package.devc.xml',
  'src/zcl_app_001.clas.abap',
  'src/zcl_app_001.clas.xml',
];

const OLD_CLASS = 'zcl_app_001';

/** Does `name` look like an ABAP class a customer may create? */
export function validClassName(name) {
  return /^[zy]c[lx]_[a-z0-9_]{1,26}$/.test(name);
}

/* The three substitutions scripts/rename.mjs makes, and no others.
 *
 * The class name is replaced in BOTH cases because the ABAP source writes it
 * lower case and the sidecar's CLSNAME upper case — that asymmetry is the
 * whole reason the template ships a script instead of an instruction. */
function rename(file, text, { cls, packageText, repo }) {
  let out = text;
  if (cls && cls !== OLD_CLASS) {
    out = out.split(OLD_CLASS).join(cls).split(OLD_CLASS.toUpperCase()).join(cls.toUpperCase());
  }
  if (packageText && file === 'src/package.devc.xml') {
    out = out.replace(/<CTEXT>[^<]*<\/CTEXT>/, `<CTEXT>${packageText}</CTEXT>`);
  }
  if (repo && file === '.abapgit.xml') {
    out = out.replace(/<NAME>[^<]*<\/NAME>/, `<NAME>${repo}</NAME>`);
  }
  return out;
}

/** The file a class ends up in, once it is not called zcl_app_001 any more. */
const renamePath = (file, cls) =>
  (cls && cls !== OLD_CLASS ? file.split(OLD_CLASS).join(cls) : file);

/**
 * Read the template out of `root` and return it as `{ path, text }` entries.
 *
 * A file the template no longer has is reported rather than skipped: this list
 * is a claim about another repository, and a silently shorter project is the
 * failure that would not be noticed until the first `npm run check`.
 */
export function scaffold(root, { cls, packageText, repo } = {}) {
  const files = [];
  const missing = [];

  for (const file of TEMPLATE_FILES) {
    const at = path.join(root, file);
    if (!fs.existsSync(at)) { missing.push(file); continue; }
    files.push({
      path: renamePath(file, cls),
      text: rename(file, fs.readFileSync(at, 'utf8'), { cls, packageText, repo }),
    });
  }

  return { files, missing };
}
